@startuml Containers
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(system, "IoT Monitoring Platform") {
    Container(api_gateway, "API Gateway", "Spring Cloud Gateway", "Маршрутизация и авторизация")
    Container(api_gateway_orchestration, "API Orchestrator", "Spring Boot", "Оркестрация: вызывает event- device- и command-сервисы")
    Container_Ext(keycloak, "Keycloak", "OAuth2", "Аутентификация и авторизация")
    Container_Ext(iot_devices, "IoT Devices", "Встраиваемые устройства", "Отправляют телеметрию и получают команды")
    Container(command_service, "Command Service", "Go+gRPC", "Принимает команды по gRPC и отдает отдельным устройствам. Работает с отдельной БД PostgreSQL")
    Container(device_service, "Device Service", "Spring Boot + ShardSphere-JDBC", "CRUD API по устройствам. Использует встроенное шардирование через JDBC")
    Container(event_service, "Event Service", "Spring Boot", "Чтение событий из Cassandra")
    Container(redis, "Redis", "In-memory cash", "Кэширование запросов")
    Container_Ext(postgresql_commands, "PostgreSQL (Commands)", "Реляционная БД", "Отдельная база для команд. Используется GO-сервисом")
    Container_Ext(postgresql_devices, "PostgreSQL (Devices)", "Реляционная БД", "Шардированная база данных устройств. Синхронная репликация каждого шарда")
    Container(cassandra, "Cassandra cluster", "NoSQL", "Хранение событий")
    Container_Ext(kafka, "Kafka cluster", "NoSQL", "event / dlt / device-id топики")
    Container(device_collector, "Device Collector", "Spring Boot", "Получает device-id, сохраняет в PostgreSQL (Devices)")
    Container(failed_events_processor, "Failed Events Processor", "Spring Boot", "DLT -> JSON в MiniO")
    Container(event_collector, "Events Collector", "Spring Boot", "Kafka -> Cassandra + device-id")
    Container(minio, "MiniO", "Объектное хранилище", "DLT -> Сохранение ошибок DLT")
}


Rel(api_gateway, api_gateway_orchestration, "Rest", "JWT")
Rel(api_gateway, keycloak, "OIDC авторизация")
Rel(iot_devices, command_service, "gRPC", "Получение команд")
Rel(api_gateway_orchestration, command_service, "gRPC", "Отправка команд")
Rel(api_gateway_orchestration, device_service, "Rest")
Rel(api_gateway_orchestration, event_service, "Rest")
Rel(api_gateway_orchestration, redis, "Кэширование")
Rel(command_service, postgresql_commands, "JDBC (write\reed)")
Rel(device_service, postgresql_devices, "Sharded JDBC (write\reed)")
Rel(event_service, cassandra, "read: события")
Rel(event_collector, cassandra, "write: события")
Rel(event_collector, kafka, "Consume: events-topic")
Rel(event_collector, kafka, "Produce: device-id-topic")
Rel(event_collector, kafka, "Produce: dlt-topic")
Rel(device_collector, kafka, "consume: device-id-topic")
Rel(device_collector, postgresql_devices, "write: device-id")
Rel(failed_events_processor, kafka, "consume: DLT-topic")
Rel(failed_events_processor, minio, "save: JSON")

@enduml