{
 "title": "Kafka Topics",
 "description": "Monitor Kafka topics and consumer groups",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kafka_brokers, namespace)"
   },
   {
    "name": "topic",
    "query": "label_values(kafka_topic_partitions{namespace=\"$namespace\"}, topic)"
   },
   {
    "name": "partition",
    "query": "label_values(kafka_topic_partition_current_offset{namespace=\"$namespace\", topic=\"$topic\"}, partition)"
   },
   {
    "name": "consumergroup",
    "query": "label_values(kafka_consumergroup_current_offset{namespace=\"$namespace\", topic=\"$topic\"}, consumergroup)"
   }
  ]
 },
 "panels": [
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Preferred leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{namespace=\"$namespace\", topic=\"$topic\"}) - sum(kafka_topic_partition_leader_is_preferred{namespace=\"$namespace\", topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "In-Sync replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas{namespace=\"$namespace\", topic=\"$topic\"}) - sum(kafka_topic_partition_in_sync_replica{namespace=\"$namespace\", topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Current offset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{namespace=\"$namespace\", topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Number of partitions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partitions{namespace=\"$namespace\", topic=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{namespace=\"$namespace\", topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Offset rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{namespace=\"$namespace\", topic=\"$topic\"}[1m]))",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Current offset",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{namespace=\"$namespace\", topic=\"$topic\"}",
     "legendFormat": "Partition {{ partition }}"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_topic_partition_under_replicated_partition{namespace=\"$namespace\", topic=\"$topic\"}",
     "legendFormat": "Partition {{ partition }}"
    }
   ]
  },
  { "title": "Partitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Preferred partition leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_leader_is_preferred{namespace=\"$namespace\", topic=\"$topic\", partition=\"$partition\"}"
    }
   ]
  },
  {
   "title": "Partition leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_leader{namespace=\"$namespace\", topic=\"$topic\", partition=\"$partition\"}"
    }
   ]
  },
  {
   "title": "Current partition offset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{namespace=\"$namespace\", topic=\"$topic\", partition=\"$partition\"}"
    }
   ]
  },
  {
   "title": "Number of partition replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_replicas{namespace=\"$namespace\", topic=\"$topic\", partition=\"$partition\"}"
    }
   ]
  },
  {
   "title": "In-Sync partition replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_in_sync_replica{namespace=\"$namespace\", topic=\"$topic\", partition=\"$partition\"}"
    }
   ]
  },
  { "title": "Consumer groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Consumer group lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=\"$namespace\", topic=\"$topic\", consumergroup=\"$consumergroup\"})",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Consumer group lag by partition",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{namespace=\"$namespace\", topic=\"$topic\", consumergroup=\"$consumergroup\"}",
     "legendFormat": "Partition {{ partition }}"
    }
   ]
  },
  {
   "title": "Consumer group lag rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_lag{namespace=\"$namespace\", topic=\"$topic\", consumergroup=\"$consumergroup\"}[1m]))",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Consumer group offset",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{namespace=\"$namespace\", topic=\"$topic\", consumergroup=\"$consumergroup\"})",
     "legendFormat": "{{ consumergroup }} offset"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{namespace=\"$namespace\", topic=\"$topic\"})",
     "legendFormat": "{{ current offset }}"
    }
   ]
  },
  {
   "title": "Consumer group offset by partition",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "kafka_consumergroup_current_offset{namespace=\"$namespace\", topic=\"$topic\", consumergroup=\"$consumergroup\"}",
     "legendFormat": "Partition {{ partition }}"
    }
   ]
  },
  {
   "title": "Consumer group offset rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{namespace=\"$namespace\", topic=\"$topic\", consumergroup=\"$consumergroup\"}[1m]))",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Topic size (not including replicas)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{namespace=\"$namespace\", topic=\"$topic\"}) / sum(kafka_topic_partition_replicas{namespace=\"$namespace\", topic=\"$topic\", partition=\"$partition\"})",
     "legendFormat": "{{ $topic }}"
    }
   ]
  },
  {
   "title": "Topic size by partition",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "expr": "kafka_log_log_size{namespace=\"$namespace\", topic=\"$topic\"}",
     "legendFormat": "{{ pod }} partition {{ partition }}"
    }
   ]
  }
 ]
}